### ISSUE TITLE
Horizontal RecyclerView in an RTL language not working correctly

### ISSUE THREAD

**Issue by Shailevy** [TheKhaeng/recycler-view-margin-decoration#1]
When the device is using an RTL language the spacing calculations are incorrect
To reproduce:
Layout manager:
RecyclerView.LayoutManager layoutManager = new LinearLayoutManager(getContext(), LinearLayoutManager.HORIZONTAL, false);

On the recycler:
addItemDecoration(new LayoutMarginDecoration(1, getContext().getResources().getDimensionPixelSize(R.dimen.something)));

The spaces won't appear in the correct places

**Comment by TheKhaeng** [comment]
I already check it for RTL language but it works for me. 😎

<img src="https://user-images.githubusercontent.com/13915498/31369545-6ea05c4e-adaf-11e7-94fe-b34176406ad4.png" width="200"> <img src="https://user-images.githubusercontent.com/13915498/31369544-6e63de2c-adaf-11e7-9e2c-4ed7fe6fc7bd.png" width="200">

**Comment by TheKhaeng** [comment]
Thank you for your feedback.
I already fix this issue. 😎

You can use V.1.2.1 right now.

**Comment by sheramin** [comment]
@TheKhaeng How did you figure it? could you please give a bit detail?
I'm working on RTL direction app, when I switch from LTR to RTL every things work fine except 'Horizontal Recyclerview' contents.
Thanks in advance,
Amin
